# Site settings
title: "Khanh's Online Journal"
description: "A blog sharing my experiences and insights on work, projects, and data."
author: Khanh Dang
email: ""
baseurl: ""
url: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Navigation
header_pages:
  - about.md
  - posts.md
  - projects.md

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Minima theme settings
minima:
  date_format: "%b %-d, %Y"
  social_links:
    github: dtbkhanh
    linkedin: dtbkhanh
    # twitter: your-twitter-username

# Additional customization
show_excerpts: true
excerpt_separator: <!--more-->

# Collections (for organizing different types of content)
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Default front matter for posts and pages
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Khanh Dang"
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
